### ISSUE TITLE
Difference between mvn.yaml and mvn_pretrain.yaml in config dir

### ISSUE THREAD

**Issue by YangJae96** [ZhengPeng7/GLCNet#6]
What is the difference?

What should I run to get the results in the paper?

**Comment by ZhengPeng7** [comment]
Run with `mvn.yaml`.
The `mvn_pretrain.yaml` was used for trying on pretraining on MovieNet-PS and then finetuning on CUHK-SYSU / PRW. It helps a lot with the detection at the beginning, but no extra improvement to the re-id.

**Comment by YangJae96** [comment]
Thanks for the answer.

In the mvn.yaml file, the BATCH_SIZE_TRAIN: 32, which means batch size is set to 32.
However, the batch size is set to 15 in the paper. Which one should I use?

Also, have you tried to use batch size=5 same as when using other datasets such as PRW and CUHK-SYSU?

**Comment by ZhengPeng7** [comment]
You can stick to the parameters in the paper since we did a lot of further modifications on the previous codes.
I think I used batch size = 5 for the MovieNet-PS, but I don't quite remember the results (maybe close to the current ones). To be honest, the performance of GLCNet on MovieNet-PS is easy to obtain. I even did not try many times for higher performance at that time.
